//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public long AwardId { get; set; }
        public string Issuer { get; set; }
        public Nullable<int> AwardMonth { get; set; }
        public Nullable<int> AwardYear { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Month Month { get; set; }
        public virtual Year Year { get; set; }
        public virtual User User { get; set; }
    }
}
