//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LpuContext : DbContext
    {
        public LpuContext()
            : base("name=LpuContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<VerifyEmail> VerifyEmails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Record> Records1 { get; set; }
        public virtual DbSet<Connection> Connections { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<WorkXp> WorkXps { get; set; }
        public virtual DbSet<Year> Years1 { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<SelfIntro> SelfIntroes { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<UserSkills> UserSkills { get; set; }
        public virtual DbSet<Online> Onlines { get; set; }
    }
}
