//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageId { get; set; }
        public Nullable<long> FromUser { get; set; }
        public Nullable<long> ToUser { get; set; }
        public string Conversations { get; set; }
        public Nullable<System.DateTime> MessageSent { get; set; }
        public Nullable<bool> Seen { get; set; }
    
        public virtual User From { get; set; }
        public virtual User To { get; set; }
    }
}
