//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectUrl { get; set; }
        public int ProjectStartMonth { get; set; }
        public int ProjectStartYear { get; set; }
        public bool ProjectOnGoing { get; set; }
        public Nullable<int> ProjectEndMonth { get; set; }
        public Nullable<int> ProjectEndYear { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual Month FromMonth { get; set; }
        public virtual Month ToMonth { get; set; }
        public virtual Year FromYear { get; set; }
        public virtual Year ToYear { get; set; }
        public virtual User User { get; set; }
    }
}
