//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserSkill
    {
        public long SkillsId { get; set; }
        public long SkillOne { get; set; }
        public long SkillTwo { get; set; }
        public Nullable<long> SkillThree { get; set; }
        public Nullable<long> SkillFour { get; set; }
        public Nullable<long> SkillFive { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual Skill SkillsOne { get; set; }
        public virtual Skill SkillsTwo { get; set; }
        public virtual Skill SkillsThree { get; set; }
        public virtual Skill SkillsFour { get; set; }
        public virtual Skill SkillsFive { get; set; }
        public virtual User User { get; set; }
    }
}
