//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkXp
    {
        public int WorkxpId { get; set; }
        public string Designation { get; set; }
        public string City { get; set; }
        public int Country { get; set; }
        public int FromMonth { get; set; }
        public int FromYear { get; set; }
        public Nullable<int> ToMonth { get; set; }
        public Nullable<int> ToYear { get; set; }
        public bool IsCurrentlyWorking { get; set; }
        public long UserId { get; set; }
        public string Company { get; set; }
    
        public virtual Country Countries { get; set; }
        public virtual Month MonthFrom { get; set; }
        public virtual Month MonthTo { get; set; }
        public virtual User User { get; set; }
        public virtual Year WorkXpStart { get; set; }
        public virtual Year WorkXpEnd { get; set; }
    }
}
